plugins {
    id "com.android.application"
}

android {
    namespace "com.example.drivetap"
    compileSdk 35

    defaultConfig {
        applicationId "com.navarrofernandez.drivetap"
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName "0.1.6"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.car.app:app:1.7.0"
}
